export enum HERO_STATES {
  PERFECT_MATCH_ALGO = 1,
  JOB_TITLE_EMPLOYER = 2,
  SKILLSETS_EMPLOYER = 3,
  YEARS_OF_EXPERIENCE_EMPLOYER = 4,
  SKILLSETS_JOBHUNTER = 5,
  YEARS_OF_EXPERIENCE_JOBHUNTER = 6,
  LOADING = 7,
  PERFECT_MATCH_RESULTS = 8,
}

export type HeroState = {
  heroState: HERO_STATES;
};
