interface Skill {
    name: string;
    isMatch: boolean;
  }
  
  interface Match {
    name: string;
    location: string;
    job: string;
    skills: Skill[];
    appliedAgo: string;
    experience: string;
    lookingFor: string[];
    salaryExpectation: string;
    language: string[];
  }
  
  export const perfectMatch: Match[] = [
    {
      name: "Olivia Davis",
      location: "London, United Kingdom",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Responsive Design", isMatch: false },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
        { name: "Tailwind CSS", isMatch: false },
        { name: "SCSS", isMatch: true },
        { name: "Rest API", isMatch: true },
      ],
      appliedAgo: "3 days ago",
      experience: "under a year",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "Mason Green",
      location: "Toronto, Canada",
      job: "Frontend Engineer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "1 week ago",
      experience: "3-5years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English", "French"]
    },
    {
      name: "Ava Martinez",
      location: "Berlin, Germany",
      job: "Junior JavaScript Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Vue.js", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "4 days ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "Spanish"]
    },
    {
      name: "Ethan Clark",
      location: "Austin, USA",
      job: "Frontend Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "SCSS", isMatch: true },
        { name: "Responsive Design", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "5 days ago",
      experience: "3-5years",
      lookingFor: ["Full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Sophia Brown",
      location: "Sydney, Australia",
      job: "UI Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Tailwind CSS", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Figma", isMatch: false },
      ],
      appliedAgo: "6 days ago",
      experience: "1-3years",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "James Wilson",
      location: "San Francisco, USA",
      job: "React Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "2 weeks ago",
      experience: "5-10years",
      lookingFor: ["Full time"],
      salaryExpectation: "$100,000-$120,000",
      language: ["English"]
    },
    {
      name: "Lucas Evans",
      location: "Madrid, Spain",
      job: "Junior Web Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Bootstrap", isMatch: false },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "3 weeks ago",
      experience: "under a year",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "negotiable",
      language: ["English", "Spanish"]
    },
    {
      name: "Isabella Hill",
      location: "Paris, France",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Vue.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "SCSS", isMatch: false },
      ],
      appliedAgo: "1 month ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "French"]
    },
    {
      "name": "Liam Parker",
      "location": "Toronto, Canada",
      "job": "Full Stack Developer",
      "skills": [
        { "name": "React", "isMatch": true },
        { "name": "Node.js", "isMatch": true },
        { "name": "Express", "isMatch": true },
        { "name": "MongoDB", "isMatch": true },
        { "name": "GraphQL", "isMatch": false },
        { "name": "TypeScript", "isMatch": false },
        { "name": "Git", "isMatch": true },
        { "name": "Docker", "isMatch": false }
      ],
      "appliedAgo": "2 weeks ago",
      "experience": "3-5years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$75,000-$90,000",
      "language": ["English"]
    },
    {
      "name": "Sophia Martinez",
      "location": "Madrid, Spain",
      "job": "UI/UX Designer",
      "skills": [
        { "name": "Figma", "isMatch": true },
        { "name": "Sketch", "isMatch": true },
        { "name": "Adobe XD", "isMatch": true },
        { "name": "CSS", "isMatch": true },
        { "name": "HTML", "isMatch": true },
        { "name": "JavaScript", "isMatch": false },
        { "name": "React", "isMatch": false },
        { "name": "Illustrator", "isMatch": true }
      ],
      "appliedAgo": "3 days ago",
      "experience": "1-3years",
      "lookingFor": ["Part time", "Contract"],
      "salaryExpectation": "$45,000-$55,000",
      "language": ["Spanish", "English"]
    },
    {
      "name": "Oliver Johnson",
      "location": "New York, USA",
      "job": "Backend Developer",
      "skills": [
        { "name": "Node.js", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "Django", "isMatch": true },
        { "name": "PostgreSQL", "isMatch": true },
        { "name": "Redis", "isMatch": false },
        { "name": "AWS", "isMatch": false },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": false }
      ],
      "appliedAgo": "1 week ago",
      "experience": "5-7years",
      "lookingFor": ["Full time"],
      "salaryExpectation": "$100,000-$120,000",
      "language": ["English"]
    },
    {
      "name": "Emma Lee",
      "location": "Seoul, South Korea",
      "job": "Mobile App Developer",
      "skills": [
        { "name": "React Native", "isMatch": true },
        { "name": "Flutter", "isMatch": true },
        { "name": "Swift", "isMatch": false },
        { "name": "Kotlin", "isMatch": true },
        { "name": "Java", "isMatch": true },
        { "name": "Git", "isMatch": true },
        { "name": "Firebase", "isMatch": false },
        { "name": "Redux", "isMatch": true }
      ],
      "appliedAgo": "2 months ago",
      "experience": "3-5years",
      "lookingFor": ["Freelance", "Remote"],
      "salaryExpectation": "$60,000-$80,000",
      "language": ["Korean", "English"]
    },
    {
      "name": "Noah Williams",
      "location": "Berlin, Germany",
      "job": "DevOps Engineer",
      "skills": [
        { "name": "AWS", "isMatch": true },
        { "name": "Terraform", "isMatch": true },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": true },
        { "name": "Jenkins", "isMatch": true },
        { "name": "Ansible", "isMatch": false },
        { "name": "Bash", "isMatch": true },
        { "name": "Python", "isMatch": false }
      ],
      "appliedAgo": "5 days ago",
      "experience": "5-7years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$85,000-$100,000",
      "language": ["German", "English"]
    },
    {
      name: "Olivia Davis",
      location: "London, United Kingdom",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Responsive Design", isMatch: false },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
        { name: "Tailwind CSS", isMatch: false },
        { name: "SCSS", isMatch: true },
        { name: "Rest API", isMatch: true },
      ],
      appliedAgo: "3 days ago",
      experience: "under a year",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "Mason Green",
      location: "Toronto, Canada",
      job: "Frontend Engineer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "1 week ago",
      experience: "3-5years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English", "French"]
    },
    {
      name: "Ava Martinez",
      location: "Berlin, Germany",
      job: "Junior JavaScript Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Vue.js", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "4 days ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "Spanish"]
    },
    {
      name: "Ethan Clark",
      location: "Austin, USA",
      job: "Frontend Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "SCSS", isMatch: true },
        { name: "Responsive Design", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "5 days ago",
      experience: "3-5years",
      lookingFor: ["Full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Sophia Brown",
      location: "Sydney, Australia",
      job: "UI Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Tailwind CSS", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Figma", isMatch: false },
      ],
      appliedAgo: "6 days ago",
      experience: "1-3years",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "James Wilson",
      location: "San Francisco, USA",
      job: "React Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "2 weeks ago",
      experience: "5-10years",
      lookingFor: ["Full time"],
      salaryExpectation: "$100,000-$120,000",
      language: ["English"]
    },
    {
      name: "Lucas Evans",
      location: "Madrid, Spain",
      job: "Junior Web Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Bootstrap", isMatch: false },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "3 weeks ago",
      experience: "under a year",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "negotiable",
      language: ["English", "Spanish"]
    },
    {
      name: "Isabella Hill",
      location: "Paris, France",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Vue.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "SCSS", isMatch: false },
      ],
      appliedAgo: "1 month ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "French"]
    },
    /* {
      "name": "Liam Parker",
      "location": "Toronto, Canada",
      "job": "Full Stack Developer",
      "skills": [
        { "name": "React", "isMatch": true },
        { "name": "Node.js", "isMatch": true },
        { "name": "Express", "isMatch": true },
        { "name": "MongoDB", "isMatch": true },
        { "name": "GraphQL", "isMatch": false },
        { "name": "TypeScript", "isMatch": false },
        { "name": "Git", "isMatch": true },
        { "name": "Docker", "isMatch": false }
      ],
      "appliedAgo": "2 weeks ago",
      "experience": "3-5years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$75,000-$90,000",
      "language": ["English"]
    },
    {
      "name": "Sophia Martinez",
      "location": "Madrid, Spain",
      "job": "UI/UX Designer",
      "skills": [
        { "name": "Figma", "isMatch": true },
        { "name": "Sketch", "isMatch": true },
        { "name": "Adobe XD", "isMatch": true },
        { "name": "CSS", "isMatch": true },
        { "name": "HTML", "isMatch": true },
        { "name": "JavaScript", "isMatch": false },
        { "name": "React", "isMatch": false },
        { "name": "Illustrator", "isMatch": true }
      ],
      "appliedAgo": "3 days ago",
      "experience": "1-3years",
      "lookingFor": ["Part time", "Contract"],
      "salaryExpectation": "$45,000-$55,000",
      "language": ["Spanish", "English"]
    },
    {
      "name": "Oliver Johnson",
      "location": "New York, USA",
      "job": "Backend Developer",
      "skills": [
        { "name": "Node.js", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "Django", "isMatch": true },
        { "name": "PostgreSQL", "isMatch": true },
        { "name": "Redis", "isMatch": false },
        { "name": "AWS", "isMatch": false },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": false }
      ],
      "appliedAgo": "1 week ago",
      "experience": "5-7years",
      "lookingFor": ["Full time"],
      "salaryExpectation": "$100,000-$120,000",
      "language": ["English"]
    },
    {
      "name": "Emma Lee",
      "location": "Seoul, South Korea",
      "job": "Mobile App Developer",
      "skills": [
        { "name": "React Native", "isMatch": true },
        { "name": "Flutter", "isMatch": true },
        { "name": "Swift", "isMatch": false },
        { "name": "Kotlin", "isMatch": true },
        { "name": "Java", "isMatch": true },
        { "name": "Git", "isMatch": true },
        { "name": "Firebase", "isMatch": false },
        { "name": "Redux", "isMatch": true }
      ],
      "appliedAgo": "2 months ago",
      "experience": "3-5years",
      "lookingFor": ["Freelance", "Remote"],
      "salaryExpectation": "$60,000-$80,000",
      "language": ["Korean", "English"]
    },
    {
      "name": "Noah Williams",
      "location": "Berlin, Germany",
      "job": "DevOps Engineer",
      "skills": [
        { "name": "AWS", "isMatch": true },
        { "name": "Terraform", "isMatch": true },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": true },
        { "name": "Jenkins", "isMatch": true },
        { "name": "Ansible", "isMatch": false },
        { "name": "Bash", "isMatch": true },
        { "name": "Python", "isMatch": false }
      ],
      "appliedAgo": "5 days ago",
      "experience": "5-7years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$85,000-$100,000",
      "language": ["German", "English"]
    },
    {
      name: "Olivia Davis",
      location: "London, United Kingdom",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Responsive Design", isMatch: false },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
        { name: "Tailwind CSS", isMatch: false },
        { name: "SCSS", isMatch: true },
        { name: "Rest API", isMatch: true },
      ],
      appliedAgo: "3 days ago",
      experience: "under a year",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "Mason Green",
      location: "Toronto, Canada",
      job: "Frontend Engineer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "1 week ago",
      experience: "3-5years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English", "French"]
    },
    {
      name: "Ava Martinez",
      location: "Berlin, Germany",
      job: "Junior JavaScript Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Vue.js", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "4 days ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "Spanish"]
    },
    {
      name: "Ethan Clark",
      location: "Austin, USA",
      job: "Frontend Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "SCSS", isMatch: true },
        { name: "Responsive Design", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "5 days ago",
      experience: "3-5years",
      lookingFor: ["Full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Sophia Brown",
      location: "Sydney, Australia",
      job: "UI Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Tailwind CSS", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Figma", isMatch: false },
      ],
      appliedAgo: "6 days ago",
      experience: "1-3years",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "James Wilson",
      location: "San Francisco, USA",
      job: "React Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "2 weeks ago",
      experience: "5-10years",
      lookingFor: ["Full time"],
      salaryExpectation: "$100,000-$120,000",
      language: ["English"]
    },
    {
      name: "Lucas Evans",
      location: "Madrid, Spain",
      job: "Junior Web Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Bootstrap", isMatch: false },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "3 weeks ago",
      experience: "under a year",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "negotiable",
      language: ["English", "Spanish"]
    },
    {
      name: "Isabella Hill",
      location: "Paris, France",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Vue.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "SCSS", isMatch: false },
      ],
      appliedAgo: "1 month ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "French"]
    },
    {
      "name": "Liam Parker",
      "location": "Toronto, Canada",
      "job": "Full Stack Developer",
      "skills": [
        { "name": "React", "isMatch": true },
        { "name": "Node.js", "isMatch": true },
        { "name": "Express", "isMatch": true },
        { "name": "MongoDB", "isMatch": true },
        { "name": "GraphQL", "isMatch": false },
        { "name": "TypeScript", "isMatch": false },
        { "name": "Git", "isMatch": true },
        { "name": "Docker", "isMatch": false }
      ],
      "appliedAgo": "2 weeks ago",
      "experience": "3-5years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$75,000-$90,000",
      "language": ["English"]
    },
    {
      "name": "Sophia Martinez",
      "location": "Madrid, Spain",
      "job": "UI/UX Designer",
      "skills": [
        { "name": "Figma", "isMatch": true },
        { "name": "Sketch", "isMatch": true },
        { "name": "Adobe XD", "isMatch": true },
        { "name": "CSS", "isMatch": true },
        { "name": "HTML", "isMatch": true },
        { "name": "JavaScript", "isMatch": false },
        { "name": "React", "isMatch": false },
        { "name": "Illustrator", "isMatch": true }
      ],
      "appliedAgo": "3 days ago",
      "experience": "1-3years",
      "lookingFor": ["Part time", "Contract"],
      "salaryExpectation": "$45,000-$55,000",
      "language": ["Spanish", "English"]
    },
    {
      "name": "Oliver Johnson",
      "location": "New York, USA",
      "job": "Backend Developer",
      "skills": [
        { "name": "Node.js", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "Django", "isMatch": true },
        { "name": "PostgreSQL", "isMatch": true },
        { "name": "Redis", "isMatch": false },
        { "name": "AWS", "isMatch": false },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": false }
      ],
      "appliedAgo": "1 week ago",
      "experience": "5-7years",
      "lookingFor": ["Full time"],
      "salaryExpectation": "$100,000-$120,000",
      "language": ["English"]
    },
    {
      "name": "Emma Lee",
      "location": "Seoul, South Korea",
      "job": "Mobile App Developer",
      "skills": [
        { "name": "React Native", "isMatch": true },
        { "name": "Flutter", "isMatch": true },
        { "name": "Swift", "isMatch": false },
        { "name": "Kotlin", "isMatch": true },
        { "name": "Java", "isMatch": true },
        { "name": "Git", "isMatch": true },
        { "name": "Firebase", "isMatch": false },
        { "name": "Redux", "isMatch": true }
      ],
      "appliedAgo": "2 months ago",
      "experience": "3-5years",
      "lookingFor": ["Freelance", "Remote"],
      "salaryExpectation": "$60,000-$80,000",
      "language": ["Korean", "English"]
    },
    {
      "name": "Noah Williams",
      "location": "Berlin, Germany",
      "job": "DevOps Engineer",
      "skills": [
        { "name": "AWS", "isMatch": true },
        { "name": "Terraform", "isMatch": true },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": true },
        { "name": "Jenkins", "isMatch": true },
        { "name": "Ansible", "isMatch": false },
        { "name": "Bash", "isMatch": true },
        { "name": "Python", "isMatch": false }
      ],
      "appliedAgo": "5 days ago",
      "experience": "5-7years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$85,000-$100,000",
      "language": ["German", "English"]
    },
    {
      name: "Olivia Davis",
      location: "London, United Kingdom",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Responsive Design", isMatch: false },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
        { name: "Tailwind CSS", isMatch: false },
        { name: "SCSS", isMatch: true },
        { name: "Rest API", isMatch: true },
      ],
      appliedAgo: "3 days ago",
      experience: "under a year",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "Mason Green",
      location: "Toronto, Canada",
      job: "Frontend Engineer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "Jest", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "1 week ago",
      experience: "3-5years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English", "French"]
    },
    {
      name: "Ava Martinez",
      location: "Berlin, Germany",
      job: "Junior JavaScript Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Vue.js", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "4 days ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "Spanish"]
    },
    {
      name: "Ethan Clark",
      location: "Austin, USA",
      job: "Frontend Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "SCSS", isMatch: true },
        { name: "Responsive Design", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "5 days ago",
      experience: "3-5years",
      lookingFor: ["Full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Sophia Brown",
      location: "Sydney, Australia",
      job: "UI Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Tailwind CSS", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "HTML", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Figma", isMatch: false },
      ],
      appliedAgo: "6 days ago",
      experience: "1-3years",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English"]
    },
    {
      name: "James Wilson",
      location: "San Francisco, USA",
      job: "React Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "Redux", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: false },
      ],
      appliedAgo: "2 weeks ago",
      experience: "5-10years",
      lookingFor: ["Full time"],
      salaryExpectation: "$100,000-$120,000",
      language: ["English"]
    },
    {
      name: "Lucas Evans",
      location: "Madrid, Spain",
      job: "Junior Web Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Webpack", isMatch: true },
        { name: "Git", isMatch: true },
        { name: "Bootstrap", isMatch: false },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "3 weeks ago",
      experience: "under a year",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "negotiable",
      language: ["English", "Spanish"]
    },
    {
      name: "Isabella Hill",
      location: "Paris, France",
      job: "Junior Front End Developer",
      skills: [
        { name: "React", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "Vue.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "SCSS", isMatch: false },
      ],
      appliedAgo: "1 month ago",
      experience: "1-3years",
      lookingFor: ["Full time"],
      salaryExpectation: "$51,000-$70,000",
      language: ["English", "French"]
    },
    {
      "name": "Liam Parker",
      "location": "Toronto, Canada",
      "job": "Full Stack Developer",
      "skills": [
        { "name": "React", "isMatch": true },
        { "name": "Node.js", "isMatch": true },
        { "name": "Express", "isMatch": true },
        { "name": "MongoDB", "isMatch": true },
        { "name": "GraphQL", "isMatch": false },
        { "name": "TypeScript", "isMatch": false },
        { "name": "Git", "isMatch": true },
        { "name": "Docker", "isMatch": false }
      ],
      "appliedAgo": "2 weeks ago",
      "experience": "3-5years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$75,000-$90,000",
      "language": ["English"]
    },
    {
      "name": "Sophia Martinez",
      "location": "Madrid, Spain",
      "job": "UI/UX Designer",
      "skills": [
        { "name": "Figma", "isMatch": true },
        { "name": "Sketch", "isMatch": true },
        { "name": "Adobe XD", "isMatch": true },
        { "name": "CSS", "isMatch": true },
        { "name": "HTML", "isMatch": true },
        { "name": "JavaScript", "isMatch": false },
        { "name": "React", "isMatch": false },
        { "name": "Illustrator", "isMatch": true }
      ],
      "appliedAgo": "3 days ago",
      "experience": "1-3years",
      "lookingFor": ["Part time", "Contract"],
      "salaryExpectation": "$45,000-$55,000",
      "language": ["Spanish", "English"]
    },
    {
      "name": "Oliver Johnson",
      "location": "New York, USA",
      "job": "Backend Developer",
      "skills": [
        { "name": "Node.js", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "Django", "isMatch": true },
        { "name": "PostgreSQL", "isMatch": true },
        { "name": "Redis", "isMatch": false },
        { "name": "AWS", "isMatch": false },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": false }
      ],
      "appliedAgo": "1 week ago",
      "experience": "5-7years",
      "lookingFor": ["Full time"],
      "salaryExpectation": "$100,000-$120,000",
      "language": ["English"]
    },
    {
      "name": "Emma Lee",
      "location": "Seoul, South Korea",
      "job": "Mobile App Developer",
      "skills": [
        { "name": "React Native", "isMatch": true },
        { "name": "Flutter", "isMatch": true },
        { "name": "Swift", "isMatch": false },
        { "name": "Kotlin", "isMatch": true },
        { "name": "Java", "isMatch": true },
        { "name": "Git", "isMatch": true },
        { "name": "Firebase", "isMatch": false },
        { "name": "Redux", "isMatch": true }
      ],
      "appliedAgo": "2 months ago",
      "experience": "3-5years",
      "lookingFor": ["Freelance", "Remote"],
      "salaryExpectation": "$60,000-$80,000",
      "language": ["Korean", "English"]
    },
    {
      "name": "Noah Williams",
      "location": "Berlin, Germany",
      "job": "DevOps Engineer",
      "skills": [
        { "name": "AWS", "isMatch": true },
        { "name": "Terraform", "isMatch": true },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": true },
        { "name": "Jenkins", "isMatch": true },
        { "name": "Ansible", "isMatch": false },
        { "name": "Bash", "isMatch": true },
        { "name": "Python", "isMatch": false }
      ],
      "appliedAgo": "5 days ago",
      "experience": "5-7years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$85,000-$100,000",
      "language": ["German", "English"]
    }       */               
  ];
  
  export const others: Match[] = [
    {
      name: "Lily Thompson",
      location: "Los Angeles, USA",
      job: "Full Stack Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: true },
        { name: "MongoDB", isMatch: true },
        { name: "Docker", isMatch: false },
        { name: "TypeScript", isMatch: true },
        { name: "REST API", isMatch: true },
      ],
      appliedAgo: "2 days ago",
      experience: "5-10years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$100,000-$120,000",
      language: ["English"]
    },
    {
      name: "Jack Baker",
      location: "Chicago, USA",
      job: "Backend Developer",
      skills: [
        { name: "Node.js", isMatch: false },
        { name: "Express", isMatch: true },
        { name: "MongoDB", isMatch: true },
        { name: "JavaScript", isMatch: true },
        { name: "GraphQL", isMatch: false },
        { name: "Docker", isMatch: true },
        { name: "REST API", isMatch: true },
        { name: "Redis", isMatch: false },
      ],
      appliedAgo: "5 days ago",
      experience: "3-5years",
      lookingFor: ["Full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Emma Johnson",
      location: "Dublin, Ireland",
      job: "Software Engineer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "TypeScript", isMatch: false },
        { name: "React", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "GraphQL", isMatch: true },
        { name: "Docker", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "MySQL", isMatch: true },
      ],
      appliedAgo: "1 week ago",
      experience: "3-5years",
      lookingFor: ["Full time", "Contract"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Noah Lee",
      location: "Seoul, South Korea",
      job: "Frontend Engineer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "Vue.js", isMatch: false },
        { name: "CSS", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "TypeScript", isMatch: true },
        { name: "Tailwind CSS", isMatch: true },
        { name: "REST API", isMatch: false },
      ],
      appliedAgo: "2 weeks ago",
      experience: "3-5years",
      lookingFor: ["full time"],
      salaryExpectation: "$71,000-$100,000",
      language: ["English"]
    },
    {
      name: "Amelia Roberts",
      location: "Tokyo, Japan",
      job: "Junior Software Developer",
      skills: [
        { name: "JavaScript", isMatch: true },
        { name: "React", isMatch: true },
        { name: "HTML", isMatch: true },
        { name: "CSS", isMatch: true },
        { name: "Node.js", isMatch: false },
        { name: "TypeScript", isMatch: false },
        { name: "Git", isMatch: true },
        { name: "Jest", isMatch: false },
      ],
      appliedAgo: "3 weeks ago",
      experience: "1-3years",
      lookingFor: ["Full time", "Part time"],
      salaryExpectation: "negotiable",
      language: ["English"]
    },
    {
      "name": "Amelia Brown",
      "location": "Sydney, Australia",
      "job": "Data Analyst",
      "skills": [
        { "name": "Python", "isMatch": true },
        { "name": "SQL", "isMatch": true },
        { "name": "Tableau", "isMatch": true },
        { "name": "Excel", "isMatch": true },
        { "name": "Power BI", "isMatch": false },
        { "name": "R", "isMatch": false },
        { "name": "Git", "isMatch": true },
        { "name": "Machine Learning", "isMatch": false }
      ],
      "appliedAgo": "4 days ago",
      "experience": "1-3years",
      "lookingFor": ["Full time", "Contract"],
      "salaryExpectation": "$50,000-$65,000",
      "language": ["English"]
    },
    {
      "name": "Lucas Nguyen",
      "location": "Ho Chi Minh City, Vietnam",
      "job": "Front End Developer",
      "skills": [
        { "name": "Vue.js", "isMatch": true },
        { "name": "JavaScript", "isMatch": true },
        { "name": "CSS", "isMatch": true },
        { "name": "HTML", "isMatch": true },
        { "name": "Nuxt.js", "isMatch": false },
        { "name": "TypeScript", "isMatch": true },
        { "name": "Sass", "isMatch": true },
        { "name": "Bootstrap", "isMatch": false }
      ],
      "appliedAgo": "3 weeks ago",
      "experience": "3-5years",
      "lookingFor": ["Part time", "Remote"],
      "salaryExpectation": "$40,000-$55,000",
      "language": ["Vietnamese", "English"]
    },
    {
      "name": "Mia Patel",
      "location": "Mumbai, India",
      "job": "Cloud Engineer",
      "skills": [
        { "name": "AWS", "isMatch": true },
        { "name": "Azure", "isMatch": false },
        { "name": "Docker", "isMatch": true },
        { "name": "Kubernetes", "isMatch": true },
        { "name": "Terraform", "isMatch": true },
        { "name": "Linux", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "Bash", "isMatch": false }
      ],
      "appliedAgo": "1 month ago",
      "experience": "5-7years",
      "lookingFor": ["Full time", "On-site"],
      "salaryExpectation": "$70,000-$85,000",
      "language": ["English", "Hindi"]
    },
    {
      "name": "Ethan Kim",
      "location": "San Francisco, USA",
      "job": "Machine Learning Engineer",
      "skills": [
        { "name": "Python", "isMatch": true },
        { "name": "TensorFlow", "isMatch": true },
        { "name": "PyTorch", "isMatch": true },
        { "name": "Scikit-learn", "isMatch": true },
        { "name": "R", "isMatch": false },
        { "name": "SQL", "isMatch": true },
        { "name": "AWS", "isMatch": true },
        { "name": "Spark", "isMatch": false }
      ],
      "appliedAgo": "2 months ago",
      "experience": "3-5years",
      "lookingFor": ["Full time", "Remote"],
      "salaryExpectation": "$110,000-$130,000",
      "language": ["English", "Korean"]
    },
    {
      "name": "Ava Davies",
      "location": "London, UK",
      "job": "Cybersecurity Specialist",
      "skills": [
        { "name": "Penetration Testing", "isMatch": true },
        { "name": "Network Security", "isMatch": true },
        { "name": "Ethical Hacking", "isMatch": true },
        { "name": "Linux", "isMatch": true },
        { "name": "Python", "isMatch": true },
        { "name": "SIEM", "isMatch": false },
        { "name": "AWS Security", "isMatch": false },
        { "name": "Firewall Configuration", "isMatch": true }
      ],
      "appliedAgo": "2 weeks ago",
      "experience": "5-7years",
      "lookingFor": ["Freelance", "Contract"],
      "salaryExpectation": "$90,000-$110,000",
      "language": ["English"]
    }                    
  ];