export interface Interview {
    id?:string;
    position: string;
    candidate?: string;
    company?: string;
    date: string;
    time: string;
    location: string;
    meetingLink?: string;
    receivedTime: string;
    sentTime?:string;
    isNew?: boolean;
    rating?: number;
    rated?: boolean;
    feedback?: string;
    reason?: string;
    status?: 'Accepted' | 'Pending' | 'Declined';
    isRequesterMe?: boolean;
    hasRescheduled?: boolean;
    bookmarked?: boolean;
    description?: string;
    coreSkills?: string[];
    experience?: string;
    employmentPreference?: string[];
    salaryExpectation?: string;
    languages?: string[];
    education?: string;
    certificate?: string;
    interpersonalSkills?: string[];
  }
  
  export interface BaseModalProps {
    isOpen: boolean;
    onClose: () => void;
    interview: Interview;
    variant?: 'employer' | 'job-hunter';
  }

export const acceptedInterviewsData: Interview[] = [/*
   {
    position: "Senior Frontend Engineer",
    candidate: "Michael Thompson",
    location: "Mountain View, CA",
    date: "December 22, 2024",
    time: "10:00 AM PST",
    meetingLink: "meet.google.com/abc-defg-hij",
    receivedTime: "2 hours ago",
    isNew: true,
    status: 'Accepted',
    coreSkills: ["React", "TypeScript", "Next.js", "CSS3", "GraphQL"],
    experience: "3-5 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$120,000-$150,000",
    languages: ["English", "Spanish"],
    education: "Master's in Computer Science",
    certificate: "AWS Certified Developer",
    interpersonalSkills: [
      "Leadership",
      "Communication",
      "Problem Solving",
      "Team Collaboration",
      "Agile Methodologies",
    ],
  },
  {
    position: "Full Stack Developer",
    candidate: "Eric Johnson",
    location: "Remote",
    date: "December 25, 2024",
    time: "1:00 PM PST",
    meetingLink: "meet.google.com/uvw-xyzq-rst",
    receivedTime: "yesterday",
    isNew: false,
    status: 'Accepted',
    coreSkills: [
      "Java",
      "Spring Boot",
      "PostgreSQL",
      "Microservices",
      "Docker",
    ],
    experience: "5-7 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$140,000-$170,000",
    languages: ["English"],
    education: "Bachelor's in Software Engineering",
    certificate: "Oracle Certified Professional Java Developer",
    interpersonalSkills: [
      "System Design",
      "Technical Leadership",
      "Mentoring",
      "Problem Solving",
      "Documentation",
    ],
  },
  {
    position: "Software Engineer",
    candidate: "Sophia Carter",
    location: "Cupertino, CA",
    date: "December 28, 2024",
    time: "11:30 AM PST",
    meetingLink: "meet.google.com/jkl-mnop-qrs",
    receivedTime: "3 days ago",
    isNew: false,
    status: 'Accepted',
    coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
    experience: "4-6 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$130,000-$160,000",
    languages: ["English", "Portuguese"],
    education: "Master's in Web Technologies",
    certificate: "MERN Stack Developer Certification",
    interpersonalSkills: [
      "Full-cycle Development",
      "Project Management",
      "Cross-functional Collaboration",
      "Code Review",
      "Mentoring",
    ],
  }, 
*/];

export const completedInterviewsData: Interview[] = [/*
   {
    position: "Senior Frontend Engineer",
    candidate: "Daniel Roberts",
    location: "Mountain View, CA",
    date: "December 22, 2024",
    time: "10:00 AM PST",
    receivedTime: "2 hours ago",
    isNew: true,
    rating: 4,
    rated: true,
    feedback: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    coreSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    experience: "3-5 years",
    employmentPreference: ["Full Time", "Hybrid"],
    salaryExpectation: "$110,000-$140,000",
    languages: ["English", "Mandarin"],
    education: "Bachelor's in Interaction Design",
    certificate: "Google UX Design Professional Certificate",
    interpersonalSkills: [
      "User-Centered Design",
      "Design Thinking",
      "Stakeholder Management",
      "Visual Communication",
      "Design Systems",
    ],
  },
  {
    position: "Full Stack Developer",
    candidate: "Emily Bennett",
    location: "Remote",
    date: "December 25, 2024",
    time: "1:00 PM PST",
    receivedTime: "yesterday",
    isNew: false,
    rated: false,
    coreSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Data Visualization",
    ],
    experience: "4-6 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$150,000-$180,000",
    languages: ["English", "French"],
    education: "Ph.D. in Data Science",
    certificate: "TensorFlow Developer Certificate",
    interpersonalSkills: [
      "Statistical Analysis",
      "Research",
      "Data Storytelling",
      "Cross-functional Communication",
      "Problem Solving",
    ],
  },
  {
    position: "Software Engineer",
    candidate: "James Anderson",
    location: "Cupertino, CA",
    date: "December 28, 2024",
    time: "11:30 AM PST",
    receivedTime: "3 days ago",
    isNew: true,
    rated: false,
    coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
    experience: "5-7 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$140,000-$170,000",
    languages: ["English", "German"],
    education: "Bachelor's in Computer Engineering",
    certificate: "Certified Kubernetes Administrator (CKA)",
    interpersonalSkills: [
      "Infrastructure Planning",
      "Security Best Practices",
      "System Architecture",
      "Team Collaboration",
      "Incident Response",
    ],
  }, 
*/];

export const declinedInterviewsData: Interview[] = [/*
   {
    position: "Sr Mobile and Web Developer",
    candidate: "John Smith",
    location: "USA",
    date: "December 20, 2024",
    time: "8:00 AM EST",
    sentTime: "today",
    receivedTime: "today",
    reason: "Not Actively Seeking",
    isNew: true,
    status: 'Declined',
    coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
    experience: "5-7 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$140,000-$170,000",
    languages: ["English", "German"],
    education: "Bachelor's in Computer Engineering",
    certificate: "Certified Kubernetes Administrator (CKA)",
    interpersonalSkills: [
      "Infrastructure Planning",
      "Security Best Practices",
      "System Architecture",
      "Team Collaboration",
      "Incident Response",
    ],
  },
  {
    position: "Full Stack Developer",
    candidate: "Emma Johnson",
    location: "Remote",
    date: "December 23, 2024",
    time: "1:00 PM EST",
    sentTime: "yesterday",
    receivedTime: "yesterday",
    reason: "Schedule Conflict",
    isNew: false,
    status: 'Declined',
    coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
    experience: "4-6 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$130,000-$160,000",
    languages: ["English", "Portuguese"],
    education: "Master's in Web Technologies",
    certificate: "MERN Stack Developer Certification",
    interpersonalSkills: [
      "Full-cycle Development",
      "Project Management",
      "Cross-functional Collaboration",
      "Code Review",
      "Mentoring",
    ],
  },
  {
    position: "Frontend Engineer",
    candidate: "Michael Brown",
    location: "Canada",
    date: "December 26, 2024",
    time: "11:30 AM EST",
    sentTime: "2 days ago",
    receivedTime: "2 days ago",
    reason: "Accepted Another Offer",
    isNew: false,
    status: 'Declined',
    coreSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Data Visualization",
    ],
    experience: "4-6 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$150,000-$180,000",
    languages: ["English", "French"],
    education: "Ph.D. in Data Science",
    certificate: "TensorFlow Developer Certificate",
    interpersonalSkills: [
      "Statistical Analysis",
      "Research",
      "Data Storytelling",
      "Cross-functional Communication",
      "Problem Solving",
    ],
  }, 
*/];

export const pendingInterviewsData: Interview[] = [/*
   {
    position: "Frontend Engineer",
    candidate: "Olivia Martinez",
    location: "Mountain View, CA",
    date: "December 22, 2024",
    time: "10:00 AM PST",
    receivedTime: "yesterday",
    isNew: true,
    coreSkills: ["React", "TypeScript", "Next.js", "CSS3", "GraphQL"],
    experience: "3-5 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$120,000-$150,000",
    languages: ["English", "Spanish"],
    education: "Master's in Computer Science",
    certificate: "AWS Certified Developer",
    interpersonalSkills: [
      "Leadership",
      "Communication",
      "Problem Solving",
      "Team Collaboration",
      "Agile Methodologies",
    ],
  },
  {
    position: "Backend Developer",
    candidate: "Benjamin Wilson",
    location: "Menlo Park, CA",
    date: "December 25, 2024",
    time: "1:00 PM PST",
    receivedTime: "two days ago",
    isNew: false,
    coreSkills: [
      "Java",
      "Spring Boot",
      "PostgreSQL",
      "Microservices",
      "Docker",
    ],
    experience: "5-7 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$140,000-$170,000",
    languages: ["English"],
    education: "Bachelor's in Software Engineering",
    certificate: "Oracle Certified Professional Java Developer",
    interpersonalSkills: [
      "System Design",
      "Technical Leadership",
      "Mentoring",
      "Problem Solving",
      "Documentation",
    ],
  },
  {
    position: "Full Stack Developer",
    candidate: "Isabella Garcia",
    location: "Remote",
    date: "January 5, 2025",
    time: "3:00 PM EST",
    receivedTime: "today",
    isNew: true,
    coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
    experience: "4-6 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$130,000-$160,000",
    languages: ["English", "Portuguese"],
    education: "Master's in Web Technologies",
    certificate: "MERN Stack Developer Certification",
    interpersonalSkills: [
      "Full-cycle Development",
      "Project Management",
      "Cross-functional Collaboration",
      "Code Review",
      "Mentoring",
    ],
  },
  {
    position: "UX/UI Designer",
    candidate: "Ethan Harris",
    location: "San Jose, CA",
    date: "January 10, 2025",
    time: "9:00 AM PST",
    receivedTime: "last week",
    isNew: false,
    coreSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    experience: "3-5 years",
    employmentPreference: ["Full Time", "Hybrid"],
    salaryExpectation: "$110,000-$140,000",
    languages: ["English", "Mandarin"],
    education: "Bachelor's in Interaction Design",
    certificate: "Google UX Design Professional Certificate",
    interpersonalSkills: [
      "User-Centered Design",
      "Design Thinking",
      "Stakeholder Management",
      "Visual Communication",
      "Design Systems",
    ],
  },
  {
    position: "Data Scientist",
    candidate: "Ava White",
    location: "Seattle, WA",
    date: "January 15, 2025",
    time: "11:00 AM PST",
    receivedTime: "two hours ago",
    isNew: true,
    coreSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Data Visualization",
    ],
    experience: "4-6 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$150,000-$180,000",
    languages: ["English", "French"],
    education: "Ph.D. in Data Science",
    certificate: "TensorFlow Developer Certificate",
    interpersonalSkills: [
      "Statistical Analysis",
      "Research",
      "Data Storytelling",
      "Cross-functional Communication",
      "Problem Solving",
    ],
  },
  {
    position: "DevOps Engineer",
    candidate: "Alexander Walker",
    location: "Redmond, WA",
    date: "January 20, 2025",
    time: "2:00 PM PST",
    receivedTime: "yesterday",
    isNew: true,
    coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
    experience: "5-7 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$140,000-$170,000",
    languages: ["English", "German"],
    education: "Bachelor's in Computer Engineering",
    certificate: "Certified Kubernetes Administrator (CKA)",
    interpersonalSkills: [
      "Infrastructure Planning",
      "Security Best Practices",
      "System Architecture",
      "Team Collaboration",
      "Incident Response",
    ],
  }, 
*/];

export const rescheduleInterviewsData: Interview[] = [/*
   {
    position: "Sr. Mobile and Web Developer",
    candidate: "Mia Lee",
    location: "USA",
    date: "December 29, 2024",
    time: "8:00 AM EST",
    receivedTime: "today",
    sentTime: "Today",
    isNew: true,
    status: "Pending",
    isRequesterMe: true,
    hasRescheduled: false,
    coreSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Data Visualization",
    ],
    experience: "4-6 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$150,000-$180,000",
    languages: ["English", "French"],
    education: "Ph.D. in Data Science",
    certificate: "TensorFlow Developer Certificate",
    interpersonalSkills: [
      "Statistical Analysis",
      "Research",
      "Data Storytelling",
      "Cross-functional Communication",
      "Problem Solving",
    ],
  },
  {
    position: "Full Stack Developer",
    candidate: "William Scott",
    location: "USA",
    date: "January 3, 2025",
    time: "2:00 PM PST",
    receivedTime: "yesterday",
    sentTime: "yesterday",
    isNew: false,
    status: "Pending",
    isRequesterMe: true,
    hasRescheduled: true,
    coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
    experience: "4-6 years",
    employmentPreference: ["Full Time", "Remote"],
    salaryExpectation: "$130,000-$160,000",
    languages: ["English", "Portuguese"],
    education: "Master's in Web Technologies",
    certificate: "MERN Stack Developer Certification",
    interpersonalSkills: [
      "Full-cycle Development",
      "Project Management",
      "Cross-functional Collaboration",
      "Code Review",
      "Mentoring",
    ],
  },
  {
    position: "Junior Front End Developer",
    candidate: "Charlotte Adams",
    location: "India",
    date: "February 1, 2025",
    time: "4:00 PM IST",
    receivedTime: "2 days ago",
    sentTime: "",
    isNew: true,
    status: "Pending",
    isRequesterMe: false,
    hasRescheduled: false,
    coreSkills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "SQL",
      "Data Visualization",
    ],
    experience: "4-6 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$150,000-$180,000",
    languages: ["English", "French"],
    education: "Ph.D. in Data Science",
    certificate: "TensorFlow Developer Certificate",
    interpersonalSkills: [
      "Statistical Analysis",
      "Research",
      "Data Storytelling",
      "Cross-functional Communication",
      "Problem Solving",
    ],
  },
  {
    position: "Jr. Web Developer",
    candidate: "Vicky Rawkus",
    location: "India",
    date: "February 1, 2025",
    time: "2:00 PM IST",
    receivedTime: "2 days ago",
    sentTime: "",
    isNew: false,
    status: "Pending",
    isRequesterMe: false,
    hasRescheduled: false,
    coreSkills: ["React", "TypeScript", "Next.js", "CSS3", "GraphQL"],
    experience: "3-5 years",
    employmentPreference: ["Full Time"],
    salaryExpectation: "$120,000-$150,000",
    languages: ["English", "Spanish"],
    education: "Master's in Computer Science",
    certificate: "AWS Certified Developer",
    interpersonalSkills: [
      "Leadership",
      "Communication",
      "Problem Solving",
      "Team Collaboration",
      "Agile Methodologies",
    ],
  }, 
*/];