export interface Match {
  id: number;
  firstName: string;
  lastName: string;
  phoneNumber?: number;
  birthday?: string;
  posted: string;
  location: string;
  position: string;
  education?: string;
  coreSkills: string[];
  experience: string;
  lookingFor: ("Full Time" | "Part Time" | "Contract only")[];
  salaryExpectation: string;
  language: string[];
  interpersonalSkills?: string[];
  certificates?: string[];
  isNew?: boolean;
}

export const perfectMatch: Match[] = [
  {
    id: 1,
    firstName: "Olivia",
    lastName: "Davis",
    phoneNumber: 639275454434,
    birthday: "March 15",
    location: "Philippines",
    position: "Junior Front End Developer",
    education: "Bachelor's Degree",
    coreSkills: ["React", "JavaScript", "HTML", "CSS", "Bootstrap"],
    posted: "1 day",
    experience: "under a year",
    lookingFor: ["Full Time", "Part Time", "Contract only"],
    salaryExpectation: "$51,000-$70,000",
    language: ["English"],
    interpersonalSkills: ["Team Collaboration", "Adaptability", "Problem Solving"],
    certificates: ["Certified JavaScript Developer"],
    isNew: true
  },
  {
    id: 2,
    firstName: "Mason",
    lastName: "Green",
    phoneNumber: 639275454435,
    birthday: "April 22",
    location: "Canada",
    position: "Frontend Engineer",
    education: "Master's Degree",
    coreSkills: ["React", "JavaScript", "CSS", "HTML", "TypeScript"],
    posted: "1 day",
    experience: "3 - 5 years",
    lookingFor: ["Full Time", "Contract only"],
    salaryExpectation: "$71,000-$100,000",
    language: ["English", "French"],
    interpersonalSkills: ["Communication", "Time Management", "Critical Thinking"],
    certificates: ["AWS Certified Developer", "TypeScript Mastery"],
    isNew: true
  },
  {
    id: 3,
    firstName: "Ava",
    lastName: "Martinez",
    phoneNumber: 639275454436,
    birthday: "July 8",
    location: "Germany",
    position: "Junior JavaScript Developer",
    education: "Bachelor's Degree",
    coreSkills: ["JavaScript", "React", "Vue.js", "CSS", "HTML"],
    posted: "2 days",
    experience: "1 - 3 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$51,000-$70,000",
    language: ["English", "Spanish"],
    interpersonalSkills: ["Creativity", "Empathy", "Conflict Resolution"],
    certificates: ["Certified Vue.js Developer"],
    isNew: false
  },
  {
    id: 4,
    firstName: "Ethan",
    lastName: "Clark",
    phoneNumber: 639275454437,
    birthday: "October 5",
    location: "United States of America",
    position: "Frontend Developer",
    education: "Master's Degree",
    coreSkills: ["React", "JavaScript", "SCSS", "Responsive Design", "Git"],
    posted: "3 days",
    experience: "3 - 5 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$71,000-$100,000",
    language: ["English"],
    interpersonalSkills: ["Leadership", "Emotional Intelligence", "Negotiation"],
    certificates: ["Google UX Design Professional Certificate"],
    isNew: false
  },
  {
    id: 5,
    firstName: "Sophia",
    lastName: "Brown",
    phoneNumber: 639275454438,
    birthday: "May 17",
    location: "Australia",
    position: "UI Developer",
    education: "Bachelor's Degree",
    coreSkills: ["React", "JavaScript", "CSS", "Tailwind CSS", "HTML"],
    posted: "5 days",
    experience: "1 - 3 years",
    lookingFor: ["Full Time", "Part Time"],
    salaryExpectation: "$51,000-$70,000",
    language: ["English"],
    interpersonalSkills: ["Team Collaboration", "Flexibility", "Persuasion"],
    certificates: ["Certified UI/UX Designer"],
    isNew: false
  },
  {
    id: 6,
    firstName: "James",
    lastName: "Wilson",
    phoneNumber: 639275454439,
    birthday: "December 12",
    location: "United States of America",
    position: "React Developer",
    education: "Master's Degree",
    coreSkills: ["React", "JavaScript", "Redux", "TypeScript", "CSS"],
    posted: "1 week",
    experience: "5 - 10 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$100,000-$120,000",
    language: ["English"],
    interpersonalSkills: ["Decision Making", "Strategic Thinking", "Innovation"],
    certificates: ["React Professional Developer"],
    isNew: false
  },
  {
    id: 7,
    firstName: "Lucas",
    lastName: "Evans",
    phoneNumber: 639275454440,
    birthday: "February 28",
    location: "Spain",
    position: "Junior Web Developer",
    education: "Associate Degree",
    coreSkills: ["React", "JavaScript", "HTML", "CSS", "Git"],
    posted: "3 weeks",
    experience: "under a year",
    lookingFor: ["Full Time", "Part Time"],
    salaryExpectation: "negotiable",
    language: ["English", "Spanish"],
    interpersonalSkills: ["Time Management", "Problem Solving", "Empathy"],
    certificates: ["Full Stack Web Development Certificates"],
    isNew: false
  },
  {
    id: 8,
    firstName: "Isabella",
    lastName: "Hill",
    phoneNumber: 639275454441,
    birthday: "August 9",
    location: "France",
    position: "Junior Front End Developer",
    education: "Bachelor's Degree",
    coreSkills: ["React", "JavaScript", "CSS", "HTML", "Git"],
    posted: "3 weeks",
    experience: "1 - 3 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$51,000-$70,000",
    language: ["English", "French"],
    interpersonalSkills: ["Adaptability", "Conflict Resolution", "Leadership"],
    certificates: ["Certified React Developer"],
    isNew: false
  },
  {
    id: 9,
    firstName: "Liam",
    lastName: "Parker",
    phoneNumber: 639275454442,
    birthday: "November 3",
    location: "Canada",
    position: "Full Stack Developer",
    education: "Master's Degree",
    coreSkills: ["React", "Node.js", "Express", "MongoDB", "Git"],
    posted: "3 weeks",
    experience: "3 - 5 years",
    lookingFor: ["Full Time", "Part Time"],
    salaryExpectation: "$75,000-$90,000",
    language: ["English"],
    interpersonalSkills: ["Creativity", "Strategic Thinking", "Emotional Intelligence"],
    certificates: ["Full Stack Developer Professional Certificate"],
    isNew: false
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Martinez",
    phoneNumber: 639275454443,
    birthday: "January 25",
    location: "Spain",
    position: "UI/UX Designer",
    education: "Bachelor's Degree",
    coreSkills: ["Figma", "Sketch", "Adobe XD", "CSS", "HTML"],
    posted: "1 month",
    experience: "1 - 3 years",
    lookingFor: ["Part Time", "Contract only"],
    salaryExpectation: "$45,000-$55,000",
    language: ["Spanish", "English"],
    interpersonalSkills: ["Flexibility", "Empathy", "Persuasion"],
    certificates: ["Certified UI/UX Designer"],
    isNew: false
  }
];

export const others: Match[] = [
  /* {
    id: 11,
    firstName: "Lily",
    lastName: "Thompson",
    phoneNumber: 639275454444,
    birthday: "September 3",
    location: "United States of America",
    position: "Full Stack Developer",
    education: "Master's Degree",
    coreSkills: ["JavaScript", "React", "GraphQL", "MongoDB", "TypeScript"],
    posted: "1 day",
    experience: "5 - 10 years",
    lookingFor: ["Full Time", "Contract only"],
    salaryExpectation: "$100,000-$120,000",
    language: ["English"],
    interpersonalSkills: ["Problem Solving", "Team Collaboration", "Adaptability"],
    certificates: ["Full Stack Professional Developer"],
    isNew: true
  },
  {
    id: 12,
    firstName: "Jack",
    lastName: "Baker",
    phoneNumber: 639275454445,
    birthday: "January 12",
    location: "United States of America",
    position: "Backend Developer",
    education: "Bachelor's Degree",
    coreSkills: ["Express", "MongoDB", "JavaScript", "Docker", "REST API"],
    posted: "2 days",
    experience: "3 - 5 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$71,000-$100,000",
    language: ["English"],
    interpersonalSkills: ["Critical Thinking", "Time Management", "Creativity"],
    certificates: ["Certified Backend Developer"],
    isNew: false
  },
  {
    id: 13,
    firstName: "Emma",
    lastName: "Johnson",
    phoneNumber: 639275454446,
    birthday: "June 28",
    location: "Ireland",
    position: "Software Engineer",
    education: "Master's Degree",
    coreSkills: ["JavaScript", "React", "GraphQL", "CSS", "MySQL"],
    posted: "1 week",
    experience: "3 - 5 years",
    lookingFor: ["Full Time", "Contract only"],
    salaryExpectation: "$71,000-$100,000",
    language: ["English"],
    interpersonalSkills: ["Leadership", "Decision Making", "Strategic Thinking"],
    certificates: ["Certified Software Engineer"],
    isNew: false
  },
  {
    id: 14,
    firstName: "Noah",
    lastName: "Lee",
    phoneNumber: 639275454447,
    birthday: "April 15",
    location: "South Korea",
    position: "Frontend Engineer",
    education: "Bachelor's Degree",
    coreSkills: ["JavaScript", "React", "CSS", "HTML", "TypeScript"],
    posted: "2 weeks",
    experience: "3 - 5 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$71,000-$100,000",
    language: ["English"],
    interpersonalSkills: ["Communication", "Emotional Intelligence", "Flexibility"],
    certificates: ["Frontend Developer Certificates"],
    isNew: false
  },
  {
    id: 15,
    firstName: "Amelia",
    lastName: "Roberts",
    phoneNumber: 639275454448,
    birthday: "July 20",
    location: "Japan",
    position: "Junior Software Developer",
    education: "Associate Degree",
    coreSkills: ["JavaScript", "React", "HTML", "CSS", "Git"],
    posted: "3 weeks",
    experience: "1 - 3 years",
    lookingFor: ["Full Time", "Part Time"],
    salaryExpectation: "Negotiable",
    language: ["English"],
    interpersonalSkills: ["Conflict Resolution", "Creativity", "Adaptability"],
    certificates: ["Certified Junior Developer"],
    isNew: false
  },
  {
    id: 16,
    firstName: "Amelia",
    lastName: "Brown",
    phoneNumber: 639275454449,
    birthday: "March 8",
    location: "Australia",
    position: "Data Analyst",
    education: "Bachelor's Degree",
    coreSkills: ["Python", "SQL", "Tableau", "Excel", "Git"],
    posted: "1 month",
    experience: "1 - 3 years",
    lookingFor: ["Full Time", "Contract only"],
    salaryExpectation: "$50,000-$65,000",
    language: ["English"],
    interpersonalSkills: ["Attention to Detail", "Analytical Thinking", "Problem Solving"],
    certificates: ["Data Analytics Professional Certificate"],
    isNew: false
  },
  {
    id: 17,
    firstName: "Lucas",
    lastName: "Nguyen",
    phoneNumber: 639275454450,
    birthday: "October 30",
    location: "Vietnam",
    position: "Front End Developer",
    education: "Bachelor's Degree",
    coreSkills: ["Vue.js", "JavaScript", "CSS", "HTML", "TypeScript"],
    posted: "1 month",
    experience: "3 - 5 years",
    lookingFor: ["Part Time", "Contract only"],
    salaryExpectation: "$40,000-$55,000",
    language: ["Vietnamese", "English"],
    interpersonalSkills: ["Empathy", "Adaptability", "Creativity"],
    certificates: ["Certified Vue.js Developer"],
    isNew: false
  },
  {
    id: 18,
    firstName: "Mia",
    lastName: "Patel",
    phoneNumber: 639275454451,
    birthday: "May 5",
    location: "India",
    position: "Cloud Engineer",
    education: "Master's Degree",
    coreSkills: ["AWS", "Docker", "Kubernetes", "Terraform", "Linux"],
    posted: "1 month",
    experience: "5 - 7 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$70,000-$85,000",
    language: ["English", "Hindi"],
    interpersonalSkills: ["Problem Solving", "Leadership", "Strategic Thinking"],
    certificates: ["AWS Certified Solutions Architect"],
    isNew: false
  },
  {
    id: 19,
    firstName: "Ethan",
    lastName: "Kim",
    phoneNumber: 639275454452,
    birthday: "December 1",
    location: "United States of America",
    position: "Machine Learning Engineer",
    education: "Doctorate/PhD",
    coreSkills: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "SQL"],
    posted: "2 months",
    experience: "3 - 5 years",
    lookingFor: ["Full Time"],
    salaryExpectation: "$110,000-$130,000",
    language: ["English", "Korean"],
    interpersonalSkills: ["Analytical Thinking", "Decision Making", "Innovation"],
    certificates: ["Certified Machine Learning Specialist"],
    isNew: false
  }, */
];