export interface Interview {
    id?:string;
    position: string;
    company: string;
    date: string;
    time: string;
    location: string;
    meetingLink?: string;
    receivedTime: string;
    sentTime?:string;
    isNew?: boolean;
    rating?: number;
    reason?: string;
    status?: 'pending';
    isRequesterMe?: boolean;
    hasRescheduled?: boolean;
    bookmarked?: boolean;
    description?: string;
    coreSkills?: string[];
    experience?: string;
    employmentPreference?: string[];
    salaryExpectation?: string;
    languages?: string[];
    education?: string;
    certificate?: string;
    interpersonalSkills?: string[];
  }
  
  export interface BaseModalProps {
    isOpen: boolean;
    onClose: () => void;
    interview: Interview;
  }

  export const acceptedInterviewsData: Interview[] = [
    {
      position: "Senior Frontend Engineer",
      company: "Google",
      location: "Mountain View, CA",
      date: "December 22, 2024",
      time: "10:00 AM PST",
      meetingLink: "meet.google.com/abc-defg-hij",
      receivedTime: "2 hours ago",
      isNew: true,
      coreSkills: [
        "Java",
        "Spring Boot",
        "PostgreSQL",
        "Microservices",
        "Docker",
      ],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English"],
      education: "Bachelor's in Software Engineering",
      certificate: "Oracle Certified Professional Java Developer",
      interpersonalSkills: [
        "System Design",
        "Technical Leadership",
        "Mentoring",
        "Problem Solving",
        "Documentation",
      ],
      description: "We are seeking a talented Front-end developer to join our developing team. You will be responsible for translating UI/UX designs into real world applications, maintaining high quality code standards, and collaborating with multi-disciplinary teams to define, design, and ship new features."
    },
    {
      position: "Full Stack Developer",
      company: "Meta",
      location: "Remote",
      date: "December 25, 2024",
      time: "1:00 PM PST",
      meetingLink: "meet.google.com/uvw-xyzq-rst",
      receivedTime: "yesterday",
      isNew: false,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
      description: "Join our dynamic team as a Full Stack Developer where you'll work on cutting-edge projects combining front-end and back-end development. You'll be involved in the complete software development lifecycle, from concept and design to testing and deployment."
    },
    {
      position: "Software Engineer",
      company: "Apple",
      location: "Cupertino, CA",
      date: "December 28, 2024",
      time: "11:30 AM PST",
      meetingLink: "meet.google.com/jkl-mnop-qrs",
      receivedTime: "3 days ago",
      isNew: false,
      coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English", "German"],
      education: "Bachelor's in Computer Engineering",
      certificate: "Certified Kubernetes Administrator (CKA)",
      interpersonalSkills: [
        "Infrastructure Planning",
        "Security Best Practices",
        "System Architecture",
        "Team Collaboration",
        "Incident Response",
      ],
      description: "We are looking for a Software Engineer to join our infrastructure team. In this role, you'll be responsible for designing and implementing scalable cloud solutions, maintaining our CI/CD pipelines, and ensuring the reliability and security of our systems."
    },
  ];

  export const completedInterviewsData: Interview[] = [
    {
      position: "Senior Frontend Engineer",
      company: "Google",
      location: "Mountain View, CA",
      date: "December 22, 2024",
      time: "10:00 AM PST",
      receivedTime: "2 hours ago",
      isNew: true,
      coreSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
      experience: "3-5 years",
      employmentPreference: ["Full Time", "Hybrid"],
      salaryExpectation: "$110,000-$140,000",
      languages: ["English", "Mandarin"],
      education: "Bachelor's in Interaction Design",
      certificate: "Google UX Design Professional Certificate",
      interpersonalSkills: [
        "User-Centered Design",
        "Design Thinking",
        "Stakeholder Management",
        "Visual Communication",
        "Design Systems",
      ],
    },
    {
      position: "Full Stack Developer",
      company: "Meta",
      location: "Remote",
      date: "December 25, 2024",
      time: "1:00 PM PST",
      receivedTime: "yesterday",
      rating: 4.5,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
    },
    {
      position: "Software Engineer",
      company: "Apple",
      location: "Cupertino, CA",
      date: "December 28, 2024",
      time: "11:30 AM PST",
      receivedTime: "3 days ago",
      rating: 4.0,
      coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English", "German"],
      education: "Bachelor's in Computer Engineering",
      certificate: "Certified Kubernetes Administrator (CKA)",
      interpersonalSkills: [
        "Infrastructure Planning",
        "Security Best Practices",
        "System Architecture",
        "Team Collaboration",
        "Incident Response",
      ],
    },
  ];

  export const declinedInterviewsData: Interview[] = [
    {
      position: "Sr Mobile and Web Developer",
      company: "Google",
      location: "USA",
      date: "December 20, 2024",
      time: "8:00 AM EST",
      sentTime: "today",
      receivedTime: "today",
      reason: "Not Actively Seeking",
      isNew: true,
      coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English", "German"],
      education: "Bachelor's in Computer Engineering",
      certificate: "Certified Kubernetes Administrator (CKA)",
      interpersonalSkills: [
        "Infrastructure Planning",
        "Security Best Practices",
        "System Architecture",
        "Team Collaboration",
        "Incident Response",
      ],
    },
    {
      position: "Full Stack Developer",
      company: "Accenture",
      location: "UAE",
      date: "December 23, 2024",
      time: "1:00 PM EST",
      sentTime: "yesterday",
      receivedTime: "yesterday",
      reason: "Schedule Conflict",
      isNew: false,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
    },
    {
      position: "Frontend Engineer",
      company: "Goodyear",
      location: "Canada",
      date: "December 26, 2024",
      time: "11:30 AM EST",
      sentTime: "2 days ago",
      receivedTime: "2 days ago",
      reason: "Accepted Another Offer",
      isNew: false,
      coreSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
      experience: "3-5 years",
      employmentPreference: ["Full Time", "Hybrid"],
      salaryExpectation: "$110,000-$140,000",
      languages: ["English", "Mandarin"],
      education: "Bachelor's in Interaction Design",
      certificate: "Google UX Design Professional Certificate",
      interpersonalSkills: [
        "User-Centered Design",
        "Design Thinking",
        "Stakeholder Management",
        "Visual Communication",
        "Design Systems",
      ],
    },
  ];

  export const pendingInterviewsData: Interview[] = [
    {
      position: "Frontend Engineer",
      company: "Google",
      location: "Mountain View, CA",
      date: "December 22, 2024",
      time: "10:00 AM PST",
      meetingLink: "https://meet.google.com/abc-defg-hij",
      receivedTime: "yesterday",
      isNew: true,
      coreSkills: ["React", "TypeScript", "Next.js", "CSS3", "GraphQL"],
      experience: "3-5 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$120,000-$150,000",
      languages: ["English", "Spanish"],
      education: "Master's in Computer Science",
      certificate: "AWS Certified Developer",
      interpersonalSkills: [
        "Leadership",
        "Communication",
        "Problem Solving",
        "Team Collaboration",
        "Agile Methodologies",
      ],
    },
    {
      position: "Backend Developer",
      company: "Meta",
      location: "Menlo Park, CA",
      date: "December 25, 2024",
      time: "1:00 PM PST",
      meetingLink: "https://meet.google.com/uvw-xyzq-rst",
      receivedTime: "two days ago",
      isNew: false,
      coreSkills: [
        "Java",
        "Spring Boot",
        "PostgreSQL",
        "Microservices",
        "Docker",
      ],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English"],
      education: "Bachelor's in Software Engineering",
      certificate: "Oracle Certified Professional Java Developer",
      interpersonalSkills: [
        "System Design",
        "Technical Leadership",
        "Mentoring",
        "Problem Solving",
        "Documentation",
      ],
    },
    {
      position: "Full Stack Developer",
      company: "Citadel",
      location: "Remote",
      date: "January 5, 2025",
      time: "3:00 PM EST",
      meetingLink: "https://meet.google.com/jkl-mnop-qrs",
      receivedTime: "today",
      isNew: true,
      coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
      experience: "4-6 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$130,000-$160,000",
      languages: ["English", "Portuguese"],
      education: "Master's in Web Technologies",
      certificate: "MERN Stack Developer Certification",
      interpersonalSkills: [
        "Full-cycle Development",
        "Project Management",
        "Cross-functional Collaboration",
        "Code Review",
        "Mentoring",
      ],
    },
    {
      position: "UX/UI Designer",
      company: "Nvidia Inc.",
      location: "San Jose, CA",
      date: "January 10, 2025",
      time: "9:00 AM PST",
      meetingLink: "https://meet.google.com/stu-vwxy-zab",
      receivedTime: "last week",
      isNew: false,
      coreSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
      experience: "3-5 years",
      employmentPreference: ["Full Time", "Hybrid"],
      salaryExpectation: "$110,000-$140,000",
      languages: ["English", "Mandarin"],
      education: "Bachelor's in Interaction Design",
      certificate: "Google UX Design Professional Certificate",
      interpersonalSkills: [
        "User-Centered Design",
        "Design Thinking",
        "Stakeholder Management",
        "Visual Communication",
        "Design Systems",
      ],
    },
    {
      position: "Data Scientist",
      company: "Open AI",
      location: "Seattle, WA",
      date: "January 15, 2025",
      time: "11:00 AM PST",
      meetingLink: "https://meet.google.com/ghi-klmn-opq",
      receivedTime: "two hours ago",
      isNew: true,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
    },
    {
      position: "DevOps Engineer",
      company: "Youtube",
      location: "Redmond, WA",
      date: "January 20, 2025",
      time: "2:00 PM PST",
      meetingLink: "https://meet.google.com/qrs-tuvw-xyz",
      receivedTime: "yesterday",
      isNew: true,
      coreSkills: ["Kubernetes", "AWS", "CI/CD", "Terraform", "Python"],
      experience: "5-7 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$140,000-$170,000",
      languages: ["English", "German"],
      education: "Bachelor's in Computer Engineering",
      certificate: "Certified Kubernetes Administrator (CKA)",
      interpersonalSkills: [
        "Infrastructure Planning",
        "Security Best Practices",
        "System Architecture",
        "Team Collaboration",
        "Incident Response",
      ],
    },
  ];

  export const rescheduleInterviewsData: Interview[] = [
    {
      position: "Sr. Mobile and Web Developer",
      company: "MAC Technofirm",
      location: "USA",
      date: "December 29, 2024",
      time: "8:00 AM EST",
      receivedTime: "today",
      sentTime: "Today",
      isNew: true,
      status: "pending",
      isRequesterMe: true,
      hasRescheduled: false,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
    },
    {
      position: "Full Stack Developer",
      company: "Neutic Labs",
      location: "USA",
      date: "January 3, 2025",
      time: "2:00 PM PST",
      receivedTime: "yesterday",
      sentTime: "yesterday",
      isNew: false,
      status: "pending",
      isRequesterMe: true,
      hasRescheduled: true,
      coreSkills: ["React", "Node.js", "MongoDB", "Express", "AWS"],
      experience: "4-6 years",
      employmentPreference: ["Full Time", "Remote"],
      salaryExpectation: "$130,000-$160,000",
      languages: ["English", "Portuguese"],
      education: "Master's in Web Technologies",
      certificate: "MERN Stack Developer Certification",
      interpersonalSkills: [
        "Full-cycle Development",
        "Project Management",
        "Cross-functional Collaboration",
        "Code Review",
        "Mentoring",
      ],
    },
    {
      position: "Junior Front End Developer",
      company: "TechSphere Solutions",
      location: "India",
      date: "February 1, 2025",
      time: "4:00 PM IST",
      receivedTime: "2 days ago",
      sentTime: "",
      isNew: true,
      status: "pending",
      isRequesterMe: false,
      hasRescheduled: false,
      coreSkills: [
        "Python",
        "Machine Learning",
        "TensorFlow",
        "SQL",
        "Data Visualization",
      ],
      experience: "4-6 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$150,000-$180,000",
      languages: ["English", "French"],
      education: "Ph.D. in Data Science",
      certificate: "TensorFlow Developer Certificate",
      interpersonalSkills: [
        "Statistical Analysis",
        "Research",
        "Data Storytelling",
        "Cross-functional Communication",
        "Problem Solving",
      ],
    },
    {
      position: "Jr. Web Developer",
      company: "CloudCred Innovations",
      location: "India",
      date: "February 1, 2025",
      time: "2:00 PM IST",
      receivedTime: "2 days ago",
      sentTime: "",
      isNew: false,
      status: "pending",
      isRequesterMe: false,
      hasRescheduled: false,
      coreSkills: ["React", "TypeScript", "Next.js", "CSS3", "GraphQL"],
      experience: "3-5 years",
      employmentPreference: ["Full Time"],
      salaryExpectation: "$120,000-$150,000",
      languages: ["English", "Spanish"],
      education: "Master's in Computer Science",
      certificate: "AWS Certified Developer",
      interpersonalSkills: [
        "Leadership",
        "Communication",
        "Problem Solving",
        "Team Collaboration",
        "Agile Methodologies",
      ],
    },
  ];