export const ROUTE_CONSTANTS = {
  // Existing routes
  ABOUT: '/about',
  FETCH: '/fetch',
  HOME: '/',
  NOT_FOUND: '/404',
  JOB_HUNTER: '/job-hunter',
  EMPLOYER: '/employer',
  JOB_LISTING: 'job-listing',
  CREATE_APPLICATION: '/create-application',
  EMPLOYER_PROFILE: 'employer-profile',
  ACCOUNT_SETTINGS_EMPLOYER: '/employer/account-settings',
  ACCOUNT_SETTINGS_JOB_HUNTER: '/job-hunter/account-settings',
  INTERVIEWS_JOB_HUNTER: '/job-hunter/interviews',
  INTERVIEWS_EMPLOYER: '/employer/interviews',
  MANAGE_JOB_LISTINGS: '/employer/manage-job-listings',
  REPORTS_ANALYTICS: '/employer/reports-and-analytics',
  BOOKMARKED_JOBS: '/job-hunter/bookmarked-jobs',
  
  FEED: 'feed',
  GENERAL: 'general',
  BILLING: 'billing',
  SUBSCRIPTION: 'subscription',
  PRIVACY: 'privacy',
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  RESCHEDULE: 'reschedule',
  DECLINED: 'declined',
  CALENDAR: 'calendar',
  ACTIVE: 'active',
  DRAFTS: 'drafts',
  EXPIRED: 'expired',
  CLOSED: 'closed',
  JOB_PERFORMANCE: 'job-performance',
  CANDIDATES: 'candidates',
  INTERVIEWS: 'interviews',
  COSTS: 'costs',
  SAVED: 'saved',
  APPLIED: 'applied'
}