export { About } from 'pages/about/About'
export { Fetch } from 'pages/fetch/Fetch'
export { Home } from 'pages/home/Home'
export { NotFound } from 'pages/not-found/NotFound'
export { JobHunter } from 'pages/job-feed/JobHunter'
export { Employer } from 'pages/job-feed/Employer'
