export { Landing } from 'pages/landing/Landing'
export { About } from 'pages/about/About'
export { Fetch } from 'pages/fetch/Fetch'
export { Home } from 'pages/home/Home'
export { NotFound } from 'pages/not-found/NotFound'

export { EmployerFeedLayout } from 'pages/employer/feed/EmployerFeedLayout'
export { JobHunterFeedLayout } from 'pages/job-hunter/feed/JobHunterFeedLayout'
export { CreateAppCard } from 'pages/job-hunter/application-form-page/CreateAppCard'
export { EditAppCard } from 'pages/job-hunter/application-form-page/EditAppCard'

export { AccountSettingsEmployer } from 'pages/employer/account-settings/AccountSettingsEmployer'
export { AccountSettingsJobHunter } from 'pages/job-hunter/account-settings/AccountSettingsJobHunter'
export { InterviewJobHunter } from 'pages/job-hunter/interviews/InterviewJobHunter'
export { InterviewEmployer } from 'pages/employer/interviews/InterviewEmployer'
export { ManageJobListings } from 'pages/employer/manage-job-listings/ManageJobListings'
export { ReportsAnalytics } from 'pages/employer/reports-analytics/ReportsAnalytics'
export { JobHunterBookmarkedJobs } from 'pages/job-hunter/bookmarked-jobs/JobHunterBookmarkedJobs'
export { CompleteProfile } from 'pages/employer/employer-profile-form/CompleteProfile'
export { JobListingFormLayout } from 'pages/employer/job-listing-form/JobListingFormLayout'
export { EditProfile} from 'pages/employer/employer-profile-form/EditProfile'

export { EmployerNotFound } from 'pages/employer/not-found/EmployerNotFound'
export { JobHunterNotFound } from 'pages/job-hunter/not-found/JobHunterNotFound'
export { NotFoundPage } from 'pages/not-found-page/NotFoundPage'
/* export { JobHunterBaseLayout } from 'pages/job-hunter/based-layout/JobHunterBaseLayout'
export { EmployerBaseLayout } from 'pages/employer/base-layout/EmployerBaseLayout' */
export { BaseLayout } from 'layouts/main-base-layout/BaseLayout'
export { SubscriptionPlan } from 'pages/subscription-plan/SubscriptionPlan'
export { EmployerBookmarkedJobs } from 'pages/employer/bookmarked-jobs/EmployerBookmarkedJobs'
export { AboutUs } from 'pages/about-us/AboutUs'
export { ContactUs } from 'pages/contact-us/ContactUs'
export { Faq } from 'pages/faq/Faq'
export { Test } from 'pages/test/Test'
export { TermsConditionsPage } from 'pages/terms-conditions/TermsConditionsPage'
export { PrivacyPolicyPage } from 'pages/privacy-policy/PrivacyPolicyPage'
export { InterruptedSubscriptionPage } from 'pages/subscription-plan/interrupted-plan/InterruptedSubscriptionPage'
