export enum MODAL_HEADER_TYPE {
  WITH_LOGO_AND_CLOSE = 1,
  WITH_CLOSE = 2,
}

export enum MODAL_STATES {
  LOGIN = 1,
  SIGNUP_SELECT_USER_TYPE = 2,
  SIGNUP_STEP2 = 3,
  SIGNUP_STEP3 = 4,
  SIGNUP_STEP4 = 5,
  SIGNUP_STEP4_EMPLOYER = 6,
  SIGNUP_STEP5 = 7,
  LOADING = 8,
  SIGNUP_CONGRATULATIONS = 9,
  AUTHNET_PAYMENT = 10,
  PERFECT_MATCH_RESULTS = 11,
  AUTHNET_PAYMENT_FULL = 12,
  FORGOT_PASSWORD_EMAIL = 13,
  FORGOT_PASSWORD_NEW_PASSWORD = 14,
  FORGOT_PASSWORD_OTP = 15,
}

export type ModalState = {
  isOpen: boolean;
  selectedModalHeader?: MODAL_HEADER_TYPE;
  modalState?: MODAL_STATES;
};
